template: Hello, %s!
defaultName: Stranger
server:
  applicationConnectors:
  - type: http
    port: 9090
  adminConnectors:
  - type: http
    port: 9091
gameServiceURL: $env:GAME_SERVICE_URL:http://localhost:9092
